name: localize_example
description: "A new Flutter project to test remote localization"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  # https://pub.dev/packages/dio
  dio: 5.1.0

  # https://pub.dev/packages/easy_localization
  easy_localization: ^3.0.5

  # https://pub.dev/packages/easy_localization_loader
  easy_localization_loader: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/locale/



